image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersionV2

build:
  verbosity: minimal
  project: Cogito.HostedWebCore.sln

artifacts:
  - path: Cogito.HostedWebCore\bin\**\*.nupkg
    name: Cogito.HostedWebCore
