version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - nuget restore
  - ps: gitversion /l console /output buildserver /UpdateVersionProperties

environment:
  PackageVersion:
    

build:
  verbosity: minimal
  project: Cogito.HostedWebCore.sln
