image: Visual Studio 2017
configuration: Release
platform: Any CPU

install:
  - choco install gitversion.portable -pre -y

before_build:
  - ps: gitversion /l console /output buildserver
  - ps: $env:PackageVersion=$env:GitVersion_NuGetVersion
  - ps: $env:AssemblyVersion=$env:GitVersion_AssemblySemVer
  - ps: $env:FileVersion=$env:GitVersion_MajorMinorPatch.0
  - ps: $env:InformationalVersion=$env:GitVersion_InformationalVersion
  - nuget restore
  - dotnet restore

build:
  verbosity: minimal
  project: Cogito.HostedWebCore.sln

artifacts:
  - path: Cogito.Web.Configuration\bin\**\*.nupkg
    name: Cogito.Web.Configuration
  - path: Cogito.IIS.Configuration\bin\**\*.nupkg
    name: Cogito.IIS.Configuration
  - path: Cogito.HostedWebCore\bin\**\*.nupkg
    name: Cogito.HostedWebCore
  - path: Cogito.HostedWebCore.ServiceFabric\bin\**\*.nupkg
    name: Cogito.HostedWebCore.ServiceFabric
